fastscore:
  fleet:
    - api: model-manage
      host: model-manage
      port: 8002
    - api: composer
      host: composer
      port: 8010
    - api: engine
      host: engine-1
      port: 8003
    - api: engine
      host: engine-2
      port: 8003
    - api: engine
      host: engine-3
      port: 8003
    - api: engine
      host: engine-4
      port: 8003
    - api: engine
      host: engine-5
      port: 8003
    - api: engine
      host: engine-6
      port: 8003

  db:
    type: mysql
    host: database
    port: 3306
    username: root
    password: root

  pneumo:
#    type: rest
    type: kafka
    bootstrap:
      - kafka:9092
    topic: notify
