# Docker compose file for the Kafka setup
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: "host"
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    network_mode: "host"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "notify:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_LOG_RETENTION_BYTES: "5000000"
      CONTROLLER_MESSAGE_QUEUE_SIZE: 1
